# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.srcs/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0.xci
# IP: The module: 'hw_rbp_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_rbp_gpio_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_rbp_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_rbp_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.srcs/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0.xci
# IP: The module: 'hw_rbp_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_rbp_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_rbp_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_rbp_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
