# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Vitis/aup-zu3-bsp/hw/constraints/mpsoc.xdc

# Block Designs: bd/hw/hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw || ORIG_REF_NAME==hw} -quiet] -quiet

# IP: bd/hw/ip/hw_PWM_0_0/hw_PWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_PWM_0_0 || ORIG_REF_NAME==hw_PWM_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_Pmod_JA_0/hw_Pmod_JA_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_Pmod_JA_0 || ORIG_REF_NAME==hw_Pmod_JA_0} -quiet] -quiet

# IP: bd/hw/ip/hw_Pmod_JAB_0/hw_Pmod_JAB_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_Pmod_JAB_0 || ORIG_REF_NAME==hw_Pmod_JAB_0} -quiet] -quiet

# IP: bd/hw/ip/hw_Pmod_JB_0/hw_Pmod_JB_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_Pmod_JB_0 || ORIG_REF_NAME==hw_Pmod_JB_0} -quiet] -quiet

# IP: bd/hw/ip/hw_audio_formatter_0_0/hw_audio_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_audio_formatter_0_0 || ORIG_REF_NAME==hw_audio_formatter_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_axi_gpio_0_0 || ORIG_REF_NAME==hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_axi_iic_aic_0/hw_axi_iic_aic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_axi_iic_aic_0 || ORIG_REF_NAME==hw_axi_iic_aic_0} -quiet] -quiet

# IP: bd/hw/ip/hw_xbar_0/hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_xbar_0 || ORIG_REF_NAME==hw_xbar_0} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_us_0/hw_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_us_0 || ORIG_REF_NAME==hw_auto_us_0} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_us_1/hw_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_us_1 || ORIG_REF_NAME==hw_auto_us_1} -quiet] -quiet

# IP: bd/hw/ip/hw_axi_interconnect_0_0/hw_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_axi_interconnect_0_0 || ORIG_REF_NAME==hw_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_i2s_receiver_0_0/hw_i2s_receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_i2s_receiver_0_0 || ORIG_REF_NAME==hw_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_i2s_transmitter_0_0/hw_i2s_transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_i2s_transmitter_0_0 || ORIG_REF_NAME==hw_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_mclk_wiz_0_0/hw_mclk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_mclk_wiz_0_0 || ORIG_REF_NAME==hw_mclk_wiz_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_proc_sys_reset_0_0/hw_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proc_sys_reset_0_0 || ORIG_REF_NAME==hw_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_axis_subset_converter_0_0/hw_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_axis_subset_converter_0_0 || ORIG_REF_NAME==hw_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_cam0_slice_0/hw_cam0_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_cam0_slice_0 || ORIG_REF_NAME==hw_cam0_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_gpio_concat_0/hw_gpio_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_gpio_concat_0 || ORIG_REF_NAME==hw_gpio_concat_0} -quiet] -quiet

# IP: bd/hw/ip/hw_gpio_out0_constant_0/hw_gpio_out0_constant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_gpio_out0_constant_0 || ORIG_REF_NAME==hw_gpio_out0_constant_0} -quiet] -quiet

# IP: bd/hw/ip/hw_gpio_out1_constant_0/hw_gpio_out1_constant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_gpio_out1_constant_0 || ORIG_REF_NAME==hw_gpio_out1_constant_0} -quiet] -quiet

# IP: bd/hw/ip/hw_gpio_out2_constant_0/hw_gpio_out2_constant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_gpio_out2_constant_0 || ORIG_REF_NAME==hw_gpio_out2_constant_0} -quiet] -quiet

# IP: bd/hw/ip/hw_grove_gpio_0/hw_grove_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_grove_gpio_0 || ORIG_REF_NAME==hw_grove_gpio_0} -quiet] -quiet

# IP: bd/hw/ip/hw_joystick_slice_0/hw_joystick_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_joystick_slice_0 || ORIG_REF_NAME==hw_joystick_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_led_slice_0/hw_led_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_led_slice_0 || ORIG_REF_NAME==hw_led_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_xbar_1/hw_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_xbar_1 || ORIG_REF_NAME==hw_xbar_1} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_0/hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_0 || ORIG_REF_NAME==hw_auto_pc_0} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_1/hw_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_1 || ORIG_REF_NAME==hw_auto_pc_1} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_2/hw_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_2 || ORIG_REF_NAME==hw_auto_pc_2} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_3/hw_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_3 || ORIG_REF_NAME==hw_auto_pc_3} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_4/hw_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_4 || ORIG_REF_NAME==hw_auto_pc_4} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_5/hw_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_5 || ORIG_REF_NAME==hw_auto_pc_5} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_6/hw_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_6 || ORIG_REF_NAME==hw_auto_pc_6} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_7/hw_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_7 || ORIG_REF_NAME==hw_auto_pc_7} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_8/hw_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_8 || ORIG_REF_NAME==hw_auto_pc_8} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_9/hw_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_9 || ORIG_REF_NAME==hw_auto_pc_9} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_10/hw_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_10 || ORIG_REF_NAME==hw_auto_pc_10} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_11/hw_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_11 || ORIG_REF_NAME==hw_auto_pc_11} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_12/hw_auto_pc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_auto_pc_12 || ORIG_REF_NAME==hw_auto_pc_12} -quiet] -quiet

# IP: bd/hw/ip/hw_ps8_0_axi_periph_0/hw_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_ps8_0_axi_periph_0 || ORIG_REF_NAME==hw_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rbp_gpio_0 || ORIG_REF_NAME==hw_rbp_gpio_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rgb0_slice_0/hw_rgb0_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rgb0_slice_0 || ORIG_REF_NAME==hw_rgb0_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rgb1_slice_0/hw_rgb1_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rgb1_slice_0 || ORIG_REF_NAME==hw_rgb1_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rgb2_slice_0/hw_rgb2_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rgb2_slice_0 || ORIG_REF_NAME==hw_rgb2_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rgb3_slice_0/hw_rgb3_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rgb3_slice_0 || ORIG_REF_NAME==hw_rgb3_slice_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rst_ps8_0_99M_0/hw_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_rst_ps8_0_99M_0 || ORIG_REF_NAME==hw_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/hw/ip/hw_system_management_wiz_0_0/hw_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_system_management_wiz_0_0 || ORIG_REF_NAME==hw_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_v_frmbuf_wr_0_0/hw_v_frmbuf_wr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_v_frmbuf_wr_0_0 || ORIG_REF_NAME==hw_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_xlconcat_0_0/hw_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_xlconcat_0_0 || ORIG_REF_NAME==hw_xlconcat_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_zynq_ultra_ps_e_0_0/hw_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==hw_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/hw_ooc.xdc
