# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.runs/synth_1/hw_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu3eg-sfvc784-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Xilinx/Vitis/aup-zu3-bsp/Src/vivado-library [current_project]
update_ip_catalog
set_property ip_output_repo c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/hdl/hw_wrapper.v
add_files C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.srcs/sources_1/bd/hw/hw.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JA_0/hw_Pmod_JA_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JA_0/hw_Pmod_JA_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JA_0/hw_Pmod_JA_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JAB_0/hw_Pmod_JAB_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JAB_0/hw_Pmod_JAB_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JAB_0/hw_Pmod_JAB_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JB_0/hw_Pmod_JB_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JB_0/hw_Pmod_JB_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_Pmod_JB_0/hw_Pmod_JB_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_audio_formatter_0_0/hw_audio_formatter_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_audio_formatter_0_0/hw_audio_formatter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_axi_iic_aic_0/hw_axi_iic_aic_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_axi_iic_aic_0/hw_axi_iic_aic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_xbar_0/hw_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_us_0/hw_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_us_0/hw_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_us_0/hw_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_us_1/hw_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_us_1/hw_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_us_1/hw_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_i2s_receiver_0_0/hw_i2s_receiver_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_i2s_receiver_0_0/hw_i2s_receiver_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_i2s_transmitter_0_0/hw_i2s_transmitter_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_i2s_transmitter_0_0/hw_i2s_transmitter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_mclk_wiz_0_0/hw_mclk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_mclk_wiz_0_0/hw_mclk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_mclk_wiz_0_0/hw_mclk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_proc_sys_reset_0_0/hw_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_proc_sys_reset_0_0/hw_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_proc_sys_reset_0_0/hw_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_axis_subset_converter_0_0/hw_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_grove_gpio_0/hw_grove_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_grove_gpio_0/hw_grove_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_grove_gpio_0/hw_grove_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_xbar_1/hw_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_0/hw_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_1/hw_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_2/hw_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_3/hw_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_4/hw_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_5/hw_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_6/hw_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_7/hw_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_8/hw_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_9/hw_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_10/hw_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_11/hw_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_12/hw_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rbp_gpio_0/hw_rbp_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rst_ps8_0_99M_0/hw_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rst_ps8_0_99M_0/hw_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_rst_ps8_0_99M_0/hw_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_system_management_wiz_0_0/hw_system_management_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_system_management_wiz_0_0/hw_system_management_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_system_management_wiz_0_0/hw_system_management_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_v_frmbuf_wr_0_0/hw_v_frmbuf_wr_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_v_frmbuf_wr_0_0/hw_v_frmbuf_wr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_zynq_ultra_ps_e_0_0/hw_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_zynq_ultra_ps_e_0_0/hw_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/hw_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Vitis/aup-zu3-bsp/hw/constraints/mpsoc.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Vitis/aup-zu3-bsp/hw/constraints/mpsoc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top hw_wrapper -part xczu3eg-sfvc784-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hw_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file hw_wrapper_utilization_synth.rpt -pb hw_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
