# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.srcs/sources_1/bd/hw/ip/hw_auto_pc_8/hw_auto_pc_8.xci
# IP: The module: 'hw_auto_pc_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_8/hw_auto_pc_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_auto_pc_8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.srcs/sources_1/bd/hw/ip/hw_auto_pc_8/hw_auto_pc_8.xci
# IP: The module: 'hw_auto_pc_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vitis/aup-zu3-bsp/hw/hw/hw.gen/sources_1/bd/hw/ip/hw_auto_pc_8/hw_auto_pc_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_auto_pc_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
